name: ves_seg
channels:
  - conda-forge
  - defaults
dependencies:
  - cuda-version=12.4
  - cudnn=9.1.1.17
  - imageio=2.37.0
  - mrcfile=1.5.4
  - pip=25.1
  - python=3.12.9
  - scikit-image=0.25.0
  - scipy=1.15.3
  - tifffile=2025.2.18
  - pip:
      - bm3d==4.0.3
      - bm4d==4.2.5
      - h5py==3.14.0
      - kornia==0.8.1
      - matplotlib==3.10.3
      - numpy==2.1.2
      - onnxruntime-gpu==1.23.0
      - opencv-python==4.12.0.88
      - pillow==11.0.0
      - six==1.17.0
      - torch==2.7.1
      - torchvision==0.22.1
      - tqdm==4.67.1
      - pyyaml
